# Generated by Django 3.2.4 on 2022-01-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0002_auto_20220130_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='Part_colour',
            new_name='part_colour',
        ),
    ]
